name: kalkulator_kpr
description: Kalkulator KPR Simulasi Kredit.

publish_to: 'none'

version: 1.2.1+9

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  loading_animation_widget: ^1.2.0+3
  overlay_loading_progress: ^1.0.1
  pattern_formatter: ^4.0.0
  intl: ^0.19.0
  upgrader: ^11.4.0
  url_launcher: ^6.1.8
  google_mobile_ads: ^6.0.0
  cached_network_image: ^3.2.3
  purchases_flutter: ^9.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  # pdf: ^3.11.3
  # easy_pdf_viewer: ^1.0.7
  path_provider: ^2.1.1
  share_plus: ^11.0.0
  # document_file_save_plus: ^2.0.0
  another_flushbar: ^1.12.30
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/menu.png
    - assets/money.png
    - assets/question.png
    - assets/flat.png
    - assets/effective.png
    - assets/anuitas.png
    - assets/ic_launcher.png
    - assets/premium.png
    - assets/premium_image.jpg
