name: kalkulator_kpr
description: Kalkulator KPR Simulasi Kredit.

publish_to: 'none'

version: 1.2.0+7

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  loading_animation_widget: ^1.2.0+3
  overlay_loading_progress: ^1.0.1
  pattern_formatter: ^2.0.0
  intl: ^0.17.0
  upgrader: ^5.1.0
  url_launcher: ^6.1.8
  google_mobile_ads: ^2.3.0
  cached_network_image: ^3.2.3
  purchases_flutter: ^5.6.4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/menu.png
    - assets/money.png
    - assets/question.png
    - assets/flat.png
    - assets/effective.png
    - assets/anuitas.png
